(function($){"use strict";function initialize(latitude,longitude,address,zoom){var latlng=new google.maps.LatLng(latitude,longitude);var myOptions={zoom:zoom,center:latlng,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:false};var map=new google.maps.Map(document.getElementById("map_canvas"),myOptions);var marker=new google.maps.Marker({position:latlng,map:map,title:"location : "+address});}
$(document).ready(function(){if($("body").hasClass("home"))
$("#dropdownMenu1").toggleClass("btn-secondary btn-default");$('.sub-menu').each(function(){$(this).parent().addClass('has-child').find('> a').append('<span class="arrow"><i class="fa fa-angle-right"></i></span>');});$('.main-menu .arrow').on('click',function(e){e.preventDefault();$(this).parents('li').find('> .sub-menu').slideToggle('fast');});$('.mobile-btn').on('click',function(){$(this).parents('.main-menu').toggleClass('open');$('body').toggleClass('menu-open');});$('html').on('click',function(e){if($(e.target).closest('.main-menu.open').length==0){$('.main-menu').removeClass('open');$('body').removeClass('menu-open');}});$('.accordion.first-open > li:first-child').addClass('open');$('.accordion-title a').on('click',function(event){event.preventDefault();if($(this).parents('li').hasClass('open')){$(this).parents('li').removeClass('open').find('.accordion-content').slideUp(400);}else{$(this).parents('.accordion').find('.accordion-content').not($(this).parents('li').find('.accordion-content')).slideUp(400);$(this).parents('.accordion').find('> li').not($(this).parents('li')).removeClass('open');$(this).parents('li').addClass('open').find('.accordion-content').slideDown(400);}});$('.site-header').sticky({topSpacing:0});var owlPreview=$('.testi-preview .owl-carousel');owlPreview.owlCarousel({nav:false,dots:true,items:1,responsive:{0:{items:1}},mouseDrag:false,touchDrag:false,animateIn:'bounceIn',animateOut:'zoomOut'});$('.twitter-slider .owl-carousel').owlCarousel({nav:false,dots:true,items:1,autoplay:true,responsive:{0:{items:1}}});$('.blog-slider').owlCarousel({nav:false,dots:true,items:3,margin:30,loop:true,autoplay:true,responsive:{0:{items:1},541:{items:2},768:{items:2},990:{items:3}}});$('.services-slider .owl-carousel').owlCarousel({nav:false,dots:true,items:4,margin:20,loop:true,autoplay:true,responsive:{0:{items:1},541:{items:2},980:{items:3},1200:{items:4}}});$('.counter-number').counterUp({delay:10,});$('.faq-list-widget a').on('click',function(e){e.preventDefault();$('.faq-list-widget a').not(this).parents('li').removeClass('active');$(this).parents('li').addClass('active');$('.faq-tab').hide();$('.faq-tab'+$(this).attr('href')).show();});$('.who-we-are .read-more').on('click',function(e){e.preventDefault();var des=$(this).attr('href').split('#section');var section=$('.home-body section:nth-child('+des[1]+')');if(section.attr('class').indexOf('light-bg')==-1){var offset=section.offset().top-100;}else{var offset=section.offset().top;}
$("html, body").animate({scrollTop:offset},700);});var address=jQuery('.contact-address').html();var width='100%';var height='500px';var zoom=16;if(address){jQuery('.contact-map').html('<div id="map_canvas" style="width:'+width+'; height:'+height+'"></div>');var geocoder=new google.maps.Geocoder();geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){var latitude=results[0].geometry.location.lat();var longitude=results[0].geometry.location.lng();initialize(latitude,longitude,address,zoom);}});}
$('.back-to-top').on('click',function(e){e.preventDefault();$("html, body").animate({scrollTop:0},700);});$(window).load(function(){$('body').addClass('loaded');setTimeout(function(){$('#page-loader').fadeOut();},500);});});})(jQuery);function setLangFR(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"fr"+"; "+expires+"; path=/";window.location.href="?lang=fr";}
function setLangEN(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"en"+"; "+expires+"; path=/";window.location.href="?lang=en";}
function setLangES(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"es"+"; "+expires+"; path=/";window.location.href="?lang=es";}
function setLangDE(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"de"+"; "+expires+"; path=/";window.location.href="?lang=de";}
function setLangPT(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"pt"+"; "+expires+"; path=/";window.location.href="?lang=pt";}
function setLangTR(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"tr"+"; "+expires+"; path=/";window.location.href="?lang=tr";}
function setLangRU(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"ru"+"; "+expires+"; path=/";window.location.href="?lang=ru";}
function setLangIT(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*100000));var expires="expires="+d.toUTCString();document.cookie="lang"+"="+"it"+"; "+expires+"; path=/";window.location.href="?lang=it";}
(function(factory){if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof module==='object'&&module.exports){module.exports=factory(require('jquery'));}else{factory(jQuery);}}(function($){var slice=Array.prototype.slice;var splice=Array.prototype.splice;var defaults={topSpacing:0,bottomSpacing:0,className:'is-sticky',wrapperClassName:'sticky-wrapper',center:false,getWidthFrom:'',widthFromWrapper:true,responsiveWidth:false,zIndex:'auto'},$window=$(window),$document=$(document),sticked=[],windowHeight=$window.height(),scroller=function(){var scrollTop=$window.scrollTop(),documentHeight=$document.height(),dwh=documentHeight-windowHeight,extra=(scrollTop>dwh)?dwh-scrollTop:0;for(var i=0,l=sticked.length;i<l;i++){var s=sticked[i],elementTop=s.stickyWrapper.offset().top,etse=elementTop-s.topSpacing-extra;if(scrollTop<=etse){if(s.currentTop!==null){s.stickyElement.css({'width':'','position':'','top':'','z-index':''});s.stickyElement.parent().removeClass(s.className);if($("body").hasClass("home"))
s.stickyElement.find("#dropdownMenu1").toggleClass("btn-secondary btn-default");s.stickyElement.trigger('sticky-end',[s]);s.currentTop=null;}}
else{var newTop=documentHeight-s.stickyElement.outerHeight()
-s.topSpacing-s.bottomSpacing-scrollTop-extra;if(newTop<0){newTop=newTop+s.topSpacing;}else{newTop=s.topSpacing;}
if(s.currentTop!==newTop){var newWidth;if(s.getWidthFrom){newWidth=$(s.getWidthFrom).width()||null;}else if(s.widthFromWrapper){newWidth=s.stickyWrapper.width();}
if(newWidth==null){newWidth=s.stickyElement.width();}
s.stickyElement.css('width',newWidth).css('position','fixed').css('top',newTop).css('z-index',s.zIndex);s.stickyElement.parent().addClass(s.className);if($("body").hasClass("home"))
s.stickyElement.find("#dropdownMenu1").toggleClass("btn-secondary btn-default");if(s.currentTop===null){s.stickyElement.trigger('sticky-start',[s]);}else{s.stickyElement.trigger('sticky-update',[s]);}
if(s.currentTop===s.topSpacing&&s.currentTop>newTop||s.currentTop===null&&newTop<s.topSpacing){s.stickyElement.trigger('sticky-bottom-reached',[s]);}else if(s.currentTop!==null&&newTop===s.topSpacing&&s.currentTop<newTop){s.stickyElement.trigger('sticky-bottom-unreached',[s]);}
s.currentTop=newTop;}
var stickyWrapperContainer=s.stickyWrapper.parent();var unstick=(s.stickyElement.offset().top+s.stickyElement.outerHeight()>=stickyWrapperContainer.offset().top+stickyWrapperContainer.outerHeight())&&(s.stickyElement.offset().top<=s.topSpacing);if(unstick){s.stickyElement.css('position','absolute').css('top','').css('bottom',0).css('z-index','');}else{s.stickyElement.css('position','fixed').css('top',newTop).css('bottom','').css('z-index',s.zIndex);}}}},resizer=function(){windowHeight=$window.height();for(var i=0,l=sticked.length;i<l;i++){var s=sticked[i];var newWidth=null;if(s.getWidthFrom){if(s.responsiveWidth){newWidth=$(s.getWidthFrom).width();}}else if(s.widthFromWrapper){newWidth=s.stickyWrapper.width();}
if(newWidth!=null){s.stickyElement.css('width',newWidth);}}},methods={init:function(options){var o=$.extend({},defaults,options);return this.each(function(){var stickyElement=$(this);var stickyId=stickyElement.attr('id');var wrapperId=stickyId?stickyId+'-'+defaults.wrapperClassName:defaults.wrapperClassName;var wrapper=$('<div></div>').attr('id',wrapperId).addClass(o.wrapperClassName);stickyElement.wrapAll(function(){if($(this).parent("#"+wrapperId).length==0){return wrapper;}});var stickyWrapper=stickyElement.parent();if(o.center){stickyWrapper.css({width:stickyElement.outerWidth(),marginLeft:"auto",marginRight:"auto"});}
if(stickyElement.css("float")==="right"){stickyElement.css({"float":"none"}).parent().css({"float":"right"});}
o.stickyElement=stickyElement;o.stickyWrapper=stickyWrapper;o.currentTop=null;sticked.push(o);methods.setWrapperHeight(this);methods.setupChangeListeners(this);});},setWrapperHeight:function(stickyElement){var element=$(stickyElement);var stickyWrapper=element.parent();if(stickyWrapper){stickyWrapper.css('height',element.outerHeight());}},setupChangeListeners:function(stickyElement){if(window.MutationObserver){var mutationObserver=new window.MutationObserver(function(mutations){if(mutations[0].addedNodes.length||mutations[0].removedNodes.length){methods.setWrapperHeight(stickyElement);}});mutationObserver.observe(stickyElement,{subtree:true,childList:true});}else{if(window.addEventListener){stickyElement.addEventListener('DOMNodeInserted',function(){methods.setWrapperHeight(stickyElement);},false);stickyElement.addEventListener('DOMNodeRemoved',function(){methods.setWrapperHeight(stickyElement);},false);}else if(window.attachEvent){stickyElement.attachEvent('onDOMNodeInserted',function(){methods.setWrapperHeight(stickyElement);});stickyElement.attachEvent('onDOMNodeRemoved',function(){methods.setWrapperHeight(stickyElement);});}}},update:scroller,unstick:function(options){return this.each(function(){var that=this;var unstickyElement=$(that);var removeIdx=-1;var i=sticked.length;while(i-->0){if(sticked[i].stickyElement.get(0)===that){splice.call(sticked,i,1);removeIdx=i;}}
if(removeIdx!==-1){unstickyElement.unwrap();unstickyElement.css({'width':'','position':'','top':'','float':'','z-index':''});}});}};if(window.addEventListener){window.addEventListener('scroll',scroller,false);window.addEventListener('resize',resizer,false);}else if(window.attachEvent){window.attachEvent('onscroll',scroller);window.attachEvent('onresize',resizer);}
$.fn.sticky=function(method){if(methods[method]){return methods[method].apply(this,slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.init.apply(this,arguments);}else{$.error('Method '+method+' does not exist on jQuery.sticky');}};$.fn.unstick=function(method){if(methods[method]){return methods[method].apply(this,slice.call(arguments,1));}else if(typeof method==='object'||!method){return methods.unstick.apply(this,arguments);}else{$.error('Method '+method+' does not exist on jQuery.sticky');}};$(function(){setTimeout(scroller,0);});}));(function(e){"use strict";e.fn.counterUp=function(t){var n=e.extend({time:400,delay:10},t);return this.each(function(){var t=e(this),r=n,i=function(){var e=[],n=r.time/r.delay,i=t.text(),s=/[0-9]+,[0-9]+/.test(i);i=i.replace(/,/g,"");var o=/^[0-9]+$/.test(i),u=/^[0-9]+\.[0-9]+$/.test(i),a=u?(i.split(".")[1]||[]).length:0;for(var f=n;f>=1;f--){var l=parseInt(i/n*f);u&&(l=parseFloat(i/n*f).toFixed(a));if(s)
while(/(\d+)(\d{3})/.test(l.toString()))l=l.toString().replace(/(\d+)(\d{3})/,"$1,$2");e.unshift(l)}
t.data("counterup-nums",e);t.text("0");var c=function(){t.text(t.data("counterup-nums").shift());if(t.data("counterup-nums").length)setTimeout(t.data("counterup-func"),r.delay);else{delete t.data("counterup-nums");t.data("counterup-nums",null);t.data("counterup-func",null)}};t.data("counterup-func",c);setTimeout(t.data("counterup-func"),r.delay)};t.waypoint(i,{offset:"100%",triggerOnce:!0})})}})(jQuery);var JCaption=function(c){var e,b,a=function(f){e=jQuery.noConflict();b=f;e(b).each(function(g,h){d(h)})},d=function(i){var h=e(i),f=h.attr("title"),j=h.attr("width")||i.width,l=h.attr("align")||h.css("float")||i.style.styleFloat||"none",g=e("<p/>",{text:f,"class":b.replace(".","_")}),k=e("<div/>",{"class":b.replace(".","_")+" "+l,css:{"float":l,width:j}});h.before(k);k.append(h);if(f!==""){k.append(g)}};a(c)};